version: '3'
services:
  database:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: mysql://user:password@database/myapp
    volumes:
      - ./backend:/app  # Add this line

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
    volumes:
      - ./frontend:/app  # Add this line
      - /app/node_modules  # This prevents overwriting node_modules with the host's

volumes:
  mysql_data:
