-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS MYAPP;

-- Use the database
USE MYAPP;

-- Create the hlasovani table
CREATE TABLE IF NOT EXISTS HLASOVANI (
    ID_HLASOVANI INT AUTO_INCREMENT PRIMARY KEY,
    VYSLEDEK_HLASOVANI TEXT NOT NULL,
    NAZEV_HLASOVANI TEXT NOT NULL,
    DATUM_HLASOVANI DATE NOT NULL
);

-- Create the osoba table
CREATE TABLE IF NOT EXISTS OSOBA (
    ID_OSOBA INT AUTO_INCREMENT PRIMARY KEY,
    JMENO_OSOBA VARCHAR(255) NOT NULL,
    PRIJMENI_OSOBA VARCHAR(255) NOT NULL
);

-- Create the poslanec table
CREATE TABLE IF NOT EXISTS POSLANEC (
    ID_POSLANEC INT AUTO_INCREMENT PRIMARY KEY,
    ID_OSOBA INT,
    FOREIGN KEY (ID_OSOBA) REFERENCES OSOBA(ID_OSOBA)
);

-- Create the poslanec_hlasovani table
CREATE TABLE IF NOT EXISTS POSLANEC_HLASOVANI (
    ID_POSLANEC INT,
    ID_HLASOVANI INT,
    VYSLEDEK VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_HLASOVANI) REFERENCES HLASOVANI(ID_HLASOVANI),
    FOREIGN KEY (ID_POSLANEC) REFERENCES POSLANEC(ID_POSLANEC),
    PRIMARY KEY (ID_POSLANEC, ID_HLASOVANI)
);

-- Create the tisky table
CREATE TABLE IF NOT EXISTS TISKY (
    ID_TISK INT AUTO_INCREMENT PRIMARY KEY,
    DRUH_TISK INT NOT NULL,
    NAZEV_TISK TEXT,
    URL_TISK TEXT NOT NULL
);

-- Create the hist table
CREATE TABLE IF NOT EXISTS HIST (
    ID_HIST INT AUTO_INCREMENT PRIMARY KEY,
    ID_TISK INT,
    ID_HLASOVANI INT,
    FOREIGN KEY (ID_TISK) REFERENCES TISKY(ID_TISK),
    FOREIGN KEY (ID_HLASOVANI) REFERENCES HLASOVANI(ID_HLASOVANI)
);